title: CFPB eProcurement

user: Myra

collections:
  procurements:
    output: true
    permalink: /sprint4a/procurements/:slug/

defaults:
  - scope:
      path: ''
      type: procurements
    values:
      layout: procurement

navigation:
  - url: /dashboard

exclude:
- '*.log'
- node_modules
- src
